py_library(
    name = "glog",
    srcs = [
        "glog/glog.py",
    ],
    imports = [
        "glog",
    ],
    deps = [
        "//py/gflags",
    ],
    visibility = [
        "//visibility:public",
    ],
)
